### PR TITLE
Bump v8-debug to 0.4.2 and v8-profiler to 5.2.4 for iojs support

### LINKED ISSUE #523: Compatibility with io.js
I installed iojs 1.0.1 x64 on windows 7 and I want to debug the code, I can not install the node-inspector successfully. How can I do with this?

The error is as follows:
```
gyp WARN install got an error, rolling back install
gyp ERR! configure error
gyp ERR! stack Error: 404 status code downloading 64-bit node.lib
gyp ERR! stack     at Request.<anonymous> (C:\Program Files\iojs\node_modules\npm\node_modules\node-gyp\lib\install.js:395:20)
gyp ERR! stack     at Request.emit (events.js:117:20)
gyp ERR! stack     at Request.onRequestResponse (C:\Program Files\iojs\node_modules\npm\node_modules\request\request.js:1255:10)
gyp ERR! stack     at ClientRequest.emit (events.js:95:17)
gyp ERR! stack     at HTTPParser.parserOnIncomingClient (_http_client.js:399:21)
gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:89:23)
gyp ERR! stack     at TLSSocket.socketOnData (_http_client.js:290:20)
gyp ERR! stack     at TLSSocket.emit (events.js:95:17)
gyp ERR! stack     at readableAddChunk (_stream_readable.js:143:16)
gyp ERR! stack     at TLSSocket.Readable.push (_stream_readable.js:106:10)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "node" "C:\\Program Files\\iojs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--name=v8-profiler" "--configuration=Release" "--module_nam
ode_modules\\node-inspector\\node_modules\\v8-profiler\\build\\profiler\\v5.2.2\\node-v42-win32-x64" "--module=C:\\Users\\george\\AppData\\Roaming\\npm\\node_modules\\node-inspector
-hosted_tarball=https://node-inspector.s3.amazonaws.com/profiler/v5.2.2/node-v42-win32-x64.tar.gz"
gyp ERR! cwd C:\Users\george\AppData\Roaming\npm\node_modules\node-inspector\node_modules\v8-profiler
gyp ERR! node -v v1.0.1
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'node-gyp.cmd rebuild --name=v8-profiler --configuration=Release --module_name=profiler --version=5.2.2 --major=5 --minor=2 --patch=
2-x64 --module=C:\Users\george\AppData\Roaming\npm\node_modules\node-inspector\node_modules\v8-profiler\build\profiler\v5.2.2\node-v42-win32-x64\profiler.node --remote_path=./profil
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\Users\george\AppData\Roaming\npm\node_modules\node-inspector\node_modules\v8-profiler\node_modules\node-pre-gyp\lib\util\
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
node-pre-gyp ERR! stack     at maybeClose (child_process.js:979:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1051:5)
node-pre-gyp ERR! System Windows_NT 6.1.7601
node-pre-gyp ERR! command "node" "C:\\Users\\george\\AppData\\Roaming\\npm\\node_modules\\node-inspector\\node_modules\\v8-profiler\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "
node-pre-gyp ERR! cwd C:\Users\george\AppData\Roaming\npm\node_modules\node-inspector\node_modules\v8-profiler
node-pre-gyp ERR! node -v v1.0.1
node-pre-gyp ERR! node-pre-gyp -v v0.5.31
node-pre-gyp ERR! not ok
Failed to execute 'node-gyp.cmd rebuild --name=v8-profiler --configuration=Release --module_name=profiler --version=5.2.2 --major=5 --minor=2 --patch=2 --runtime=node --node_abi=nod
AppData\Roaming\npm\node_modules\node-inspector\node_modules\v8-profiler\build\profiler\v5.2.2\node-v42-win32-x64\profiler.node --remote_path=./profiler/v5.2.2/ --package_name=node-
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\iojs\\\\node.exe" "C:\\Program Files\\iojs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "node-inspector"
npm ERR! node v1.0.1
npm ERR! npm  v2.1.18
npm ERR! code ELIFECYCLE

npm ERR! v8-debug@0.3.3 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the v8-debug@0.3.3 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! This is most likely a problem with the v8-debug package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get their info via:
npm ERR!     npm owner ls v8-debug
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\george\npm-debug.log
```

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/7747195-compatibility-with-io-js?utm_campaign=plugin&utm_content=tracker%2F195817&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F195817&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by jimthedev**
Fixes #523.

### CODE REVIEW

**Comment by bajtos** [comment]
@3y3 PTAL

**Comment by jimthedev** [comment]
As I noted here: https://github.com/node-inspector/v8-debug/pull/12#issuecomment-75100634

I need to update this PR once both my debug and profiler prs are merged to see if tests finish in CI. They do finish locally when both v8 deps use at least node-pre-gyp 0.6.4

**Comment by 3y3** [comment]
`v8-debug 0.4.1` and `v8-profiler 5.2.4` released.
I'll ready to merge this pr, after updating it.

**Comment by jimthedev** [comment]
I'm having trouble figuring out why the startProfiler test is failing. Is seems like everything is properly set up. Can anyone else have a look?

**Comment by 3y3** [comment]
> I'm having trouble figuring out why the startProfiler test is failing. Is seems like everything is properly set up. Can anyone else have a look?

This is out of scope of this commit. I work on this issue in current time. In `v8-debug 0.4.2` I fixed completely main blocking issue for Node Inspector's new features (https://github.com/joyent/node/issues/9156).

I don't understand why tests  doesn't pass for Profiler and HeapProfiler API after v8-debug 0.4.2, but it's not so important now.

Please update v8-debug to 0.4.2 in commit.
Also we don't use dirty merging in node-inspector - please use rebase for clean commit history.

**Comment by jimthedev** [comment]
Ok @3y3 cleaned up my history and changed the version to 0.4.2. Will wait for you on the profiler test failures.

**Comment by 3y3** [comment]
Landed as 08001e1a37a6e375ff56ee6d71ac2d8560d5cb25
Thank you!

**Pull request closed without merging**
