### PR TITLE
Updated frontend: added browser redirect from "/" root to proper inspector URI.

### PR DESCRIPTION
**Pull request by marcominetti**

### CODE REVIEW

**Comment by bajtos** [comment]
I am proposing to drop `/debug` path from the URL and server the debugger UI directly on the root URL.

```diff
- http://localhost:8080/debug?ws=localhost:8080&port=5858
+ http://localhost:8080/?ws=localhost:8080&port=5858
```

@3y3 @auchenberg What's your opinion? Are you aware of any reason why the root URL may not work?

**Comment by 3y3** [comment]
I don't see any reasons to continue work on `/debug` path.
+1 to drop it (with backward compatibility).

**Comment by marcominetti** [comment]
If @auchenberg agrees, I change this pr to drop it

**Comment by bajtos** [comment]
@marcominetti let's not wait for @auchenberg and move this patch forward. Could you please rework the code to serve the debugger at the root url, as discussed above?

**Comment by marcominetti** [comment]
@bajtos Yep, I should have time this afternoon or evening to carry out all ni related tasks... (CEST)

**Comment by auchenberg** [comment]
Looks good. I don't have any problem with removing /debug, as long it won't
cause problems with /json or future endpoints.

**Comment by bajtos** [comment]
> As long it won't cause problems with /json or future endpoints.

I think there should not be any problems. The (new) handler is supposed to serve only `GET /`, everything else should remain unchanged.

**Comment by marcominetti** [comment]
done @bajtos

**Comment by bajtos** [comment]
Landed via 21dee3d, I have modified the patch to update README too. Thank you for the contribution!

**Pull request closed without merging**
