### PR TITLE
Fix --hidden option for NODE_DEBUG mode

### PR DESCRIPTION
**Pull request by 3y3**

### CODE REVIEW

**Comment by bajtos** [comment]
The change LGTM. Could you please check why the tests are failing on Travis? I had restarted v0.10 job to see if it was a timing issue only.

**Comment by 3y3** [comment]
Travis uses 0.10.35 with corrupted debugger

**Comment by bajtos** [comment]
Oh, I see. Is it worth chaning `.travis.yml` to force Node v0.10.33 and thus fix the build?

**Comment by 3y3** [comment]
> Oh, I see. Is it worth chaning .travis.yml to force Node v0.10.33 and thus fix the build?

To fix all tests we need to use 0.10.33 and 0.11.13 (current 0.11.14 config downloads prebuild binaries for 0.11.13 and fails. I'll fix this issue in next `v8-debug` version. So we can't publish prebuild binaries for 0.11.14 - there is node-pre-gyp issue with Win x64 build)

**Comment by bajtos** [comment]
I am more concerned about v0.10. I am ok with ignoring failing 0.11 tests for now, as long as we have at least single platform that is passing...

**Comment by bajtos** [comment]
BTW we should probably deprioritize support for v0.11 and focus more on io.js (a.k.a node 1.0). Unfortunately Travis does not support it OOTB, see https://github.com/iojs/io.js/issues/364 and https://github.com/creationix/nvm/issues/590

**Comment by samccone** [comment]
:+1: this fixes #498

**Comment by bajtos** [comment]
@3y3 let's not worry about the CI in this PR and ship the fix to the users. Do you have time to land & release this PR, or shall I do it myself?

**Comment by bajtos** [comment]
The CI build will be fixed by #532.

**Pull request merged**
