### PR TITLE
travis: fix Node versions

### PR DESCRIPTION
**Pull request by bajtos**
- Use v0.10.33 to prevent debugger-related regressions in .34 and .35
- Use v0.11.13 because v0.11.14 is not supported by v8-debug yet.

/to @3y3 thoughts?

> To fix all tests we need to use 0.10.33 and 0.11.13 (current 0.11.14 config downloads prebuild binaries for 0.11.13 and fails. I'll fix this issue in next v8-debug version. So we can't publish prebuild binaries for 0.11.14 - there is node-pre-gyp issue with Win x64 build)

[v0.11.15](http://nodejs.org/dist/v0.11.15/) has been released on 20.1., it may be best to skip 0.11.14 and update v8-debug for 0.11.15. BTW the rumours say that v0.11.15 will become v0.12.0 in two weeks or so.

### CODE REVIEW

**Comment by bajtos** [comment]
The CI passes on both v0.10 and v0.11 with this patch in place.

**Comment by 3y3** [comment]
I reviewed some changes in 0.11.15 yesterday. Best news for me - new debugger agent in this release.
I already updated `nan` version to 1.5.* and `node-pre-gyp` to 0.6.* in v8-debug, now I need to do it in v8-profiler and we'll be compatible with 0.11.15.

io.js issue in `nvm` was closed. So now we can try to add io to CI testing in subprojects and after this in node-inspector.

**Comment by 3y3** [comment]
Oh, sure - LGTM! Please merge also my fix.

**Comment by bajtos** [comment]
> io.js issue in nvm was closed. So now we can try to add io to CI testing in subprojects and after this in node-inspector.

IMO we need to wait until the Travis part https://github.com/travis-ci/travis-ci/issues/3108 is implemented too.

**Comment by 3y3** [comment]
Dirty merge =(

**Comment by bajtos** [comment]
Yeah, I forgot that we don't use the merge button in Node Inspector. Sorry for that, I'll be more careful in the future.

**Pull request merged**
