### PR TITLE
Update frontend

### PR DESCRIPTION
**Pull request by 3y3**

### CODE REVIEW

**Comment by 3y3** [comment]
@bajtos , tt's ready to test and review. I added `for tests` commit, because travis switch to 0.11.14 version by default, and we have prebuild binaries only for uncompatible 0.11.13 (I can't publish binaries for 0.11.14 automatically, because there is no win x64 release version). Also we wait 0.10.36.

**Comment by bajtos** [comment]
@3y3 What's the best way how to review this patch? What are the important things to check?

The last time I was upgrading front-end, I reviewed the diff of the old and the new version to catch any code changes that may affect the front-end. Have you done the same? If not, how did you verify that no regression is introduced by the upgrade?

**Comment by 3y3** [comment]
> The last time I was upgrading front-end, I reviewed the diff of the old and the new version to catch any code changes that may affect the front-end. Have you done the same?

This is impossible - big part of files removed, other part renamed and replaced. I only tested that existed interface works correctly.

So I was digging each problem, that I found.

One important thing in this path - I don't use overrides for web socket.
(Look at `Use default web socket to connect to inspector backend` (38e3b43)).

There used default socket connection, therefore old way to open console was deprecated.
(Look at`Extend protocol by Console.showConsole`(4fd2ad3))

Profiling API converted to async style (I also updated `v8-debug` API with `registerCommandAsync`)

Each other commit adds new implementation of existed overriding and removes old impl.
Last commit (`Deprecate unuseful front-end changes`) removes all changes that are not useful for new frontend, in other words I can't find how to use this changes. 

Finally now we need to send main context info to frontend (now devTools works with some contexts in one window (main + workers))
(Look at `Send page context to frontend` (e231659))

Please check that SaveLiveEdit works correctly for you. This is one of very problematic places.

**Comment by bajtos** [comment]
I reviewed all commits except the front-end update itself, you did a great job!

See my comments above, most of them are concerned about coding style.

I did not test the new version yet, I'll try to do that ASAP, ideally today/tomorrow.

**Comment by bajtos** [comment]
> Please check that SaveLiveEdit works correctly for you. This is one of very problematic places.

It does not work :(

Also the page title is wrong, I see `Developer Tools - file://<path-to-app.js>`

**Comment by 3y3** [comment]
Rebased to master.

@jakub-g , can you please look at this pr. There exists bug for you.
Now our inspector link is `http://examlpe.com:8080/debug?port=5858&ws=example.com:8080`
This link doesn't work on Windows with `node-debug` command for reason of unescaped `&`.
Original issue in `opener` https://github.com/domenic/opener/issues/9 (It will be nice, if you fix also this issue)

But current issue for you - unhandled error event:
```
D:\GIT\node-inspector [frontend]> node bin/node-debug index
Node Inspector is now available from http://127.0.0.1:8080/debug?ws=127.0.0.1:80
80&port=5858
Debugging `index`

Command failed: cmd /c start "" http://127.0.0.1:8080/debug?ws=127.0.0.1:8080&po
rt=5858
"port" ?? ?????? ???????? ??? ?????
????????, ??????? ?????? ??? ???????? ????.

Please open the URL manually in Chrome/Chromium/Opera or similar browser
Debugger listening on port 5858
events.js:73
      throw er; // Unhandled 'error' event
            ^
Error: read ECONNRESET
    at exports._errnoException (util.js:732:11)
    at TCP.onread (net.js:530:26)
```

@bajtos , now I will work on `saveLiveEdit`. Will be nice if you provide me some failure test.
(But in current time I can live without it)

@marcominetti, @auchenberg , I see that you already rebased to this pr. Any thoughts about `saveLiveEdit`?

**Comment by marcominetti** [comment]
@3y3 what's wrong with saveLiveEdit? I've never tested it. I usually disable inspector's liveedit cause I'm implementing live coding at application server layer in my project.

**Comment by auchenberg** [comment]
@3y3 I haven't had a look at ``saveLiveEdit`` yet.

**Comment by jakub-g** [comment]
@3y3 I will try to find some time and have a look soon

**Comment by marcominetti** [comment]
Hi there, I've just spend a few time onbuilding awareness of the saveLiveEdit related stuff.

It seems to me that the live edit triggers (within the backend lib):
1. generate a request for the debugger client of type "changelive" through DebuggerAgent.setScriptSource
1.1. try to update call frames for breakpoints/frontend through DebuggerAgent._handleChangeLiveOrRestartFrameResponse
1.2. flush new source code to disk through DebuggerAgent._persistScriptChanges

But where is or should be implemented 'changelive' request handler in debugger? Is it "changelive" a V8 debugger feature?

**Comment by 3y3** [comment]
> Is it "changelive" a V8 debugger feature?

Yes. Look at [debug-debugger](https://github.com/joyent/node/blob/master/deps/v8/src/debug-debugger.js#L2324-L2369)

**Comment by marcominetti** [comment]
Cool. Great. I'll delve into it...

**Comment by bajtos** [comment]
@3y3 I am not sure what do you need from me at this point. Do you need me to test the updated front-end and especially live edit? Review the modified code? Something else?

**Comment by bajtos** [comment]
@3y3 could you also squash "fixup" commits? It will make my review easier.

**Comment by marcominetti** [comment]
Hi there, to start working on the plugin system #582 I'm reviewing the @3y3 pulled front-end branch. Is there anyone working on that or an updated fork? I started working on cleaning the UI from useless and not-working stuff (and fixed two leftovers causing exceptions).

**Comment by 3y3** [comment]
Ok. I finish inspection of live edit. There is no new problems with this feature, i.e. it works for me on some scripts. But for some other (for example `periodicConsoleLog`) it doesn't work correctly (I can reproduce this behavior on 0.7.4), so this problem is out of scope of this pr (and maybe out of scope of node-inspector).

So, I rebased pr to master. I also added fix for `repeatMessageCounter`.

@bajtos , please review.

>I started working on cleaning the UI from useless and not-working stuff

@marcominetti , you can prepare this as next pr after frontend will be merged.
So I think that `frontend` is ready to merge and we'll do it soon.

**Comment by jakub-g** [comment]
@3y3 new versions of `opener` and `biased-opener` were released, you will get them after `npm install`. I keep in mind unhandled error, will come back to it when I have a spare minute.

**Comment by 3y3** [comment]
@jakub-g , good news thank you!

**Comment by bajtos** [comment]
I reviewed again. Unfortunately my previous comments were lost, so I did only a quick check for obvious issues. 

Note that I don't have enough time to test that the new front-end is working well, especially in edge cases, I'll leave that out to other volunteers (probably after the change has landed on master).

For posterity, I am cross-posting my new comments below.

> front-end-node/NodeInspectorOverrides.js in 33b5709

Is it worth adding a new method for this? IMO it's ok to define these overrides directly in the constructor.

```js
WebInspector.NodeInspectorOverrides = function() {
   this._overridenStrings = {
     '(no domain)' : '(core modules)'
   };
   // etc.
};
```

>  tools/generate-front-end.js in ea513f0

This is very weird. `extedModulesBy` is reading `./front-end/inspector.json` and here you are overwriting that file.

Can we keep the auto-generated files in `./front-end-node` please? It will also make it easier to compare our version with the original version (IMO).

>  lib/ConsoleAgent.js in 39329bf

AFAICT, this commit is making two changes:
 1. Same messages are no longer grouped together. Is this because the front-end performs grouping now?
 2. `clearMessages` is no longer cleaning the cache. I am wondering why we cannot clear the cache? Is there a way how to access a cleared message from the UI? My concern is that the cache can grow too much during a longer debugging session.

**Comment by pflannery** [comment]
I see this message when I first load node-inspector in chrome. (I'm using iojs 1.6.2.)

     Your Node version (undefined) has a partial support of profiler.
     The stack frames tree doesn't show all stack frames due to low sampling rate.
     The profiling data is incomplete and may show misleading results.
     Update Node to 0.11.13 or newer to get full support.


Sometimes when I stop on a break point and "Resume execution with F8" it hops to the console tab but doesn't always go back when it hits another breakpoint, I then see this message 

    Runtime.getProperties failed.
    Object #-3# not found

but I can continue to debug so its not major issue.

Finally, CPU profiling is recording data but you cant leave the profile tab because all tabs become disabled once recording has started.

Otherwise everything is working great, I can hover over arrays + strings and they are shown correctly in the popup and I can also work in the console.
I'm going to keep using this version and will report anything else I find here. 

Thanks doing the work on this, so far so great ;)

**Comment by marcominetti** [comment]
hi @3y3, any news on latest feedback from @bajtos?

**Comment by 3y3** [comment]
@bajtos , so I rebased lot of commits for

>This is very weird. extedModulesBy is reading ./front-end/inspector.json and here you are overwriting that file.

All other changes I maked in fixups:
> 1. Same messages are no longer grouped together. Is this because the front-end performs grouping now?
2. clearMessages is no longer cleaning the cache. I am wondering why we cannot clear the cache? Is there a way how to access a cleared message from the UI? My concern is that the cache can grow too much during a longer debugging session.

The second case was a bug - fixed in 71cb859

Last two fixups is for
>Is it worth adding a new method for this? IMO it's ok to define these overrides directly in the constructor.

I'll squash fixups after review (or, if you want, before it).

**Comment by bajtos** [comment]
@3y3 great! This patch is good to be landed, please don't forget to squash the fixup commits before merging.

**Comment by bajtos** [comment]
@3y3 Could you please also check why the build is failing? I cannot tell whether the failures are related to this pull request or not. I am fine with landing this patch as it is and investigating build failures later.

**Comment by 3y3** [comment]
@bajtos , ok I'll fix test for console API and merge this pr.

**Comment by marcominetti** [comment]
Great! I'll pull request all fixes...

@3y3 my fix/xxx branches are not anymore in sync with master but they were synced with your frontend branch? how can i resync against master? (sorry but i'm still new in prs... oops)

**Comment by 3y3** [comment]
@marcominetti , I merged this pr. You are free to open your prs now! Please start from smaller =)

**Comment by 3y3** [comment]
@marcominetti , you can try next:
If `node-inspector/node-inspector` is your `upstream` remote
```
git fetch upstream
git checkout fix/...
git rebase -i upstream master
```

There you receive a list of your commits ahead of master. Comment all that in not a part of your changes

```
# This is changes from outdated frontend branch. Comment all they
#pick f69a4be Send page context to frontend
#pick 858f96d Extend noop commands list
#pick 6e4cf12 Added PageAgent canEmulate and canScreencast callbacks
#pick bf39568 Disable unusable tabs
#pick bb51b00 Allow to save modified files
#pick a85761f Reload frontend on detach
#pick ef1a754 Fix ProfilerAgent relative to new protocol.json
#pick b15f403 Fix HeapProfilerAgent relative to new protocol.json
#pick 60bc509 Deprecate unuseful front-end changes
#pick 6479407 Fix console messageRepeatCounter

pick 6479407 LOOK HERE. THIS IS YOUR CHANGES.
```

So, you are synced with my outdated `frontend` and there can be some small conflicts during rebase that you'll need to fix manually.

**Comment by marcominetti** [comment]
Ok, quite standard way then... ;)

**Pull request merged**
