### PR TITLE
fix(front-end): DOMExtension, isEnterKey

### PR DESCRIPTION
**Pull request by iamfrontender**
Seems that a lot of time passed since last front-end synchronisation with ChromeDevTools.
Looks like full upgrade would be a proper fix.

### CODE REVIEW

**Comment by iamfrontender** [comment]
Fixes #903 though

**Comment by iamfrontender** [comment]
It's not a proper fix. More of a workaround. 
Proper fix would be to integrate with latest ChromeDevTools frontend. It'd fix broken F8, arrows and the rest of issues people are having after upgrading from Chrome 51.

**Comment by ryanspillsbury90** [comment]
This is a big headache for a lot of people. Please consider merging this in and doing the proper fix later on. Thanks

**Comment by iamfrontender** [comment]
@ryanspillsbury90 , just to prevent you from wasting time. This one is unlikely to be merged, repo doesn't look maintained.

**Comment by Mido22** [comment]
Yeah, just checked the last commit seems to be on April 9 :(

**Comment by cgadam** [comment]
@iamfrontender I saw that your workaround solves the problem of the Enter not working in the console, however, if I assign something new to an already existing variable the value does not get reflected. Do you know why that might happen?

This same thing does not happens if you define the variable in the console, but it does happens for existing ones:

Variables defined in console

<pre>
var aVar = 2
undefined
aVar
2
aVar = 3
3
aVar
3
<pre>

versus

Variables already defined in the code and trying to overwrite its value during a breakpoint:
<pre>
ip
"1.1.1.1"
ip='Hello'
"Hello"
ip
"1.1.1.1"
<pre>

**Comment by a7madgamal** [comment]
any updates?

**Comment by mmrko** [comment]
Just to add to the discussion above, I'm using the following `sed` statement to patch the Enter key support for the time being:

```bash
sed -i 's/return event.keyCode !== 229 && event.keyIdentifier === "Enter";/return (event.keyCode !== 229 \&\& event.keyIdentifier === "Enter") || event.keyCode === 13;/' node_modules/node-inspector/front-end/platform/DOMExtension.js
```

**Comment by codeHatcher** [comment]
I'm waiting for this PR as well. I think an entire community is actually

**Comment by a7madgamal** [comment]
I hope someone updates this great tool, it's missing A LOT from the current devtools 😿

**Comment by hustxiaoc** [comment]
duplicate  https://github.com/node-inspector/node-inspector/pull/955

**Pull request closed without merging**
