### PR TITLE
fix: support node 6.4.x and above

### PR DESCRIPTION
**Pull request by hustxiaoc**
since node  6.4.0, the project doesn't work anymore, this pr will fix this!

### CODE REVIEW

**Comment by hustxiaoc** [comment]
@3y3 @Miroslav Bajtoš @Danny Coates

**Comment by bajtos** [comment]
Hello, I am afraid neither of us have bandwidth to maintain this project :(

My recommendation is to use 0.7.x version of Node Inspector - it doesn't inject any code to the debugged applications; or update to Node 6.3+ and use `node --inspect` together with Chrome DevTools (see e.g. https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V6.md#2016-07-06-version-630-current-fishrock123).

**Comment by hustxiaoc** [comment]
Thanks for the replying, but this can be still very useful in some occasions,  we have been using it for online debug all the time.   It really helps a lot. So could you please  put me on the maintainer list and  I'm very glad to maintain this project with you guys~

**Comment by bajtos** [comment]
>  Could you please put me on the maintainer list and I would be very glad to maintain this project with you guys :)

Of course! Please check your inbox for an invitation sent by GitHub.

**Comment by hustxiaoc** [comment]
moved to https://github.com/node-inspector/node-inspector/pull/990

**Pull request closed without merging**
